from __future__ import annotations

import importlib
from pathlib import Path

from pi_memory.db.base import Base
from pi_memory.db.database import Database
from pi_memory.db.models import ensure_models_registered
from sqlalchemy import inspect
from sqlalchemy.orm import configure_mappers

EXPECTED_CONSTANT_NAMES = (
    "JOB_KIND_PROCESS_TRANSCRIPT",
    "JOB_KIND_SUMMARIZE_TOOL_ACTIVITIES",
    "JOB_KIND_INTERPRET_SESSION",
    "JOB_KIND_ASSESS_INTERPRETATION_QUALITY",
    "JOB_KIND_PROJECT_MEMORY_RECORDS",
    "JOB_KIND_PROMOTE_DURABLE_MEMORY",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_CLAIMED",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_COMPLETED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUSES",
    "ANALYSIS_KIND_TRANSCRIPT_STRUCTURE",
    "ANALYSIS_STATUS_RUNNING",
    "ANALYSIS_STATUS_COMPLETED",
    "ANALYSIS_STATUS_FAILED",
    "ANALYSIS_STATUS_CANCELLED",
    "ANALYSIS_STATUSES",
    "ACTIVITY_KIND_USER_TEXT",
    "ACTIVITY_KIND_ASSISTANT_TEXT",
    "ACTIVITY_KIND_ASSISTANT_THINKING",
    "ACTIVITY_KIND_TOOL_PAIR",
    "ACTIVITY_KIND_PENDING_TOOL_CALL",
    "ACTIVITY_KIND_ORPHAN_TOOL_RESULT",
    "ACTIVITY_KIND_COMPACTION",
    "ACTIVITY_KIND_SESSION_EVENT",
    "ACTIVITY_KIND_CUSTOM_EVENT",
    "ACTIVITY_KINDS",
    "ACTIVITY_TEXT_KIND_DETERMINISTIC",
    "ACTIVITY_TEXT_KIND_TOOL_SUMMARY",
    "ACTIVITY_TEXT_KIND_UNAVAILABLE",
    "ACTIVITY_TEXT_KINDS",
    "ACTIVITY_TEXT_STATUS_PENDING",
    "ACTIVITY_TEXT_STATUS_COMPLETED",
    "ACTIVITY_TEXT_STATUS_SKIPPED",
    "ACTIVITY_TEXT_STATUS_FAILED",
    "ACTIVITY_TEXT_STATUSES",
    "EPISODE_STATUS_OPEN",
    "EPISODE_STATUS_CLOSED",
    "EPISODE_STATUSES",
    "EPISODE_CLOSE_REASON_COMPACTION",
    "EPISODE_CLOSE_REASON_TIME_GAP",
    "EPISODE_CLOSE_REASON_TRANSCRIPT_END",
    "EPISODE_CLOSE_REASON_CURRENT_CURSOR",
    "EPISODE_CLOSE_REASONS",
    "SESSION_SNAPSHOT_STATUS_READY_FOR_INTERPRETATION",
    "SESSION_SNAPSHOT_STATUSES",
    "SESSION_INTERPRETATION_STATUS_COMPLETED",
    "SESSION_INTERPRETATION_STATUS_BLOCKED",
    "SESSION_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES",
    "SESSION_INTERPRETATION_STATUSES",
    "EPISODE_INTERPRETATION_STATUS_COMPLETED",
    "EPISODE_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES",
    "EPISODE_INTERPRETATION_STATUS_FAILED",
    "EPISODE_INTERPRETATION_STATUSES",
    "SESSION_INTERPRETATION_BLOCKED_REASON_PHASE_5A_NOT_READY",
    "SESSION_INTERPRETATION_BLOCKED_REASON_PARENT_TRANSCRIPT_NOT_INGESTED",
    "SESSION_INTERPRETATION_BLOCKED_REASON_SOURCE_ORIGIN_INCOMPLETE",
    "SESSION_INTERPRETATION_BLOCKED_REASONS",
    "SESSION_INTERPRETATION_QUALITY_STATUS_HEALTHY",
    "SESSION_INTERPRETATION_QUALITY_STATUS_DEGRADED",
    "SESSION_INTERPRETATION_QUALITY_STATUS_FAILED",
    "SESSION_INTERPRETATION_QUALITY_STATUS_NOT_ASSESSED",
    "SESSION_INTERPRETATION_QUALITY_STATUS_ASSESSMENT_FAILED",
    "SESSION_INTERPRETATION_QUALITY_STATUSES",
    "SESSION_INTERPRETATION_QUALITY_REASON_BLOCKED_INTERPRETATION",
    "SESSION_INTERPRETATION_QUALITY_REASON_SKIPPED_NO_CLAIM_SOURCES",
    "SESSION_INTERPRETATION_QUALITY_REASON_OUTDATED_DERIVATION",
    "SESSION_INTERPRETATION_QUALITY_REASON_SUPERSEDED_SNAPSHOT",
    "SESSION_INTERPRETATION_QUALITY_REASON_DETERMINISTIC_INTEGRITY_FAILED",
    "SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_DEGRADED",
    "SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_FAILED",
    "SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_PENDING",
    "SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_FAILED",
    "SESSION_INTERPRETATION_QUALITY_REASONS",
    "SESSION_INTERPRETATION_DERIVATION_STATUS_CURRENT",
    "SESSION_INTERPRETATION_DERIVATION_STATUS_OUTDATED",
    "SESSION_INTERPRETATION_DERIVATION_STATUS_SUPERSEDED",
    "SESSION_INTERPRETATION_DERIVATION_STATUSES",
    "SESSION_INTERPRETATION_DETERMINISTIC_STATUS_PASSED",
    "SESSION_INTERPRETATION_DETERMINISTIC_STATUS_FAILED",
    "SESSION_INTERPRETATION_DETERMINISTIC_STATUS_NOT_APPLICABLE",
    "SESSION_INTERPRETATION_DETERMINISTIC_STATUSES",
    "SESSION_INTERPRETATION_SEMANTIC_STATUS_PASSED",
    "SESSION_INTERPRETATION_SEMANTIC_STATUS_DEGRADED",
    "SESSION_INTERPRETATION_SEMANTIC_STATUS_FAILED",
    "SESSION_INTERPRETATION_SEMANTIC_STATUS_NOT_ASSESSED",
    "SESSION_INTERPRETATION_SEMANTIC_STATUS_ASSESSMENT_FAILED",
    "SESSION_INTERPRETATION_SEMANTIC_STATUSES",
    "SOURCE_ORIGIN_LOCAL",
    "SOURCE_ORIGIN_INHERITED",
    "SOURCE_ORIGIN_MIXED",
    "SOURCE_ORIGIN_UNKNOWN",
    "SOURCE_ORIGINS",
    "DURABLE_MEMORY_STATUS_CANDIDATE",
    "DURABLE_MEMORY_STATUS_PROMOTED",
    "DURABLE_MEMORY_STATUS_QUARANTINED",
    "DURABLE_MEMORY_STATUS_REJECTED",
    "DURABLE_MEMORY_STATUS_ARCHIVED",
    "DURABLE_MEMORY_STATUSES",
    "DURABLE_MEMORY_ARCHIVED_REASON_SUPERSEDED",
    "DURABLE_MEMORY_ARCHIVED_REASON_STALE",
    "DURABLE_MEMORY_ARCHIVED_REASON_MANUALLY_RETIRED",
    "DURABLE_MEMORY_ARCHIVED_REASON_SOURCE_INVALIDATED",
    "DURABLE_MEMORY_ARCHIVED_REASONS",
    "DURABLE_MEMORY_RELATION_TYPE_NOVEL",
    "DURABLE_MEMORY_RELATION_TYPE_DUPLICATE",
    "DURABLE_MEMORY_RELATION_TYPE_REINFORCES",
    "DURABLE_MEMORY_RELATION_TYPE_REFINES",
    "DURABLE_MEMORY_RELATION_TYPE_CONFLICTS",
    "DURABLE_MEMORY_RELATION_TYPE_SUPERSEDES",
    "DURABLE_MEMORY_RELATION_TYPE_STALE_SIGNAL",
    "DURABLE_MEMORY_RELATION_TYPES",
    "DURABLE_MEMORY_SOURCE_KIND_CLAIM",
    "DURABLE_MEMORY_SOURCE_KIND_SUPPORTING_CONTEXT",
    "DURABLE_MEMORY_SOURCE_KINDS",
    "MEMORY_PROJECTION_COLLECTION_NAME",
    "MEMORY_PROJECTION_RECORD_TYPE_SESSION_CLAIM",
    "MEMORY_PROJECTION_RECORD_TYPE_DURABLE_MEMORY",
    "MEMORY_PROJECTION_RECORD_TYPES",
    "MEMORY_LAYER_SHORT_TERM",
    "MEMORY_LAYER_LONG_TERM",
    "MEMORY_LAYERS",
    "MEMORY_PROJECTION_STATUS_PENDING",
    "MEMORY_PROJECTION_STATUS_INDEXED",
    "MEMORY_PROJECTION_STATUS_STALE",
    "MEMORY_PROJECTION_STATUS_FAILED",
    "MEMORY_PROJECTION_STATUS_DELETED",
    "MEMORY_PROJECTION_STATUSES",
)

EXPECTED_MODEL_NAMES = (
    "ActivityUnit",
    "AnalysisRun",
    "DurableMemoryAuditEvent",
    "DurableMemoryItem",
    "DurableMemoryRelation",
    "DurableMemorySource",
    "Episode",
    "EpisodeInterpretationSnapshot",
    "EpisodeManifest",
    "Job",
    "MemoryProjectionRecord",
    "MemorySession",
    "Observation",
    "SessionInterpretationQualityReport",
    "SessionInterpretationSnapshot",
    "SessionSnapshotShell",
    "Transcript",
    "TranscriptEntry",
)

EXPECTED_TABLE_NAMES = {
    "activity_units",
    "analysis_runs",
    "durable_memory_audit_events",
    "durable_memory_items",
    "durable_memory_relations",
    "durable_memory_sources",
    "episode_interpretation_snapshots",
    "episode_manifests",
    "episodes",
    "jobs",
    "memory_projection_records",
    "observations",
    "session_interpretation_quality_reports",
    "session_interpretation_snapshots",
    "session_snapshot_shells",
    "sessions",
    "transcript_entries",
    "transcripts",
}


def sqlite_url(path: Path) -> str:
    return f"sqlite:///{path}"


def test_constants_module_contains_expected_names() -> None:
    constants = importlib.import_module("pi_memory.constants")

    missing = [name for name in EXPECTED_CONSTANT_NAMES if not hasattr(constants, name)]

    assert missing == []


def test_models_package_contains_expected_models() -> None:
    models = importlib.import_module("pi_memory.db.models")

    missing = [name for name in EXPECTED_MODEL_NAMES if not hasattr(models, name)]

    assert missing == []


def test_base_metadata_registers_expected_tables() -> None:
    ensure_models_registered()

    assert set(Base.metadata.tables) == EXPECTED_TABLE_NAMES


def test_schema_mappers_configure() -> None:
    configure_mappers()


def test_database_initialize_creates_registered_tables(tmp_path: Path) -> None:
    database = Database(sqlite_url(tmp_path / "memory.db"))
    try:
        database.initialize()
        table_names = set(inspect(database.engine).get_table_names())
    finally:
        database.close_if_open()

    assert EXPECTED_TABLE_NAMES.issubset(table_names)
