"""Constants for the Pi memory service."""

from pathlib import Path
from typing import Final

SERVICE_NAME: Final = "pi-memory"
SERVICE_VERSION: Final = "0.1.0"

DEFAULT_HOST: Final = "127.0.0.1"
DEFAULT_PORT: Final = 8765

MEMORY_DIR: Final = Path("~/.pi/memory").expanduser()
MEMORY_DB_PATH: Final = MEMORY_DIR / "memory.db"
MEMORY_DB_URL: Final = f"sqlite:///{MEMORY_DB_PATH}"
MEMORY_CHROMA_DIR: Final = MEMORY_DIR / "chroma"
MEMORY_MODEL_CACHE_DIR: Final = MEMORY_DIR / "models"
SERVER_METADATA_PATH: Final = MEMORY_DIR / "server.json"
SERVER_LOCK_PATH: Final = MEMORY_DIR / "server.lock"
LOGS_DIR: Final = MEMORY_DIR / "logs"

JOB_KIND_PROCESS_TRANSCRIPT = "process_transcript"
JOB_KIND_SUMMARIZE_TOOL_ACTIVITIES = "summarize_tool_activities"
JOB_KIND_INTERPRET_SESSION = "interpret_session"
JOB_KIND_ASSESS_INTERPRETATION_QUALITY = "assess_interpretation_quality"
JOB_KIND_PROJECT_MEMORY_RECORDS = "project_memory_records"
JOB_KIND_PROMOTE_DURABLE_MEMORY = "promote_durable_memory"

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_CLAIMED = "claimed"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUSES = (
    JOB_STATUS_QUEUED,
    JOB_STATUS_CLAIMED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_CANCELLED,
)

ANALYSIS_KIND_TRANSCRIPT_STRUCTURE = "transcript_structure"
ANALYSIS_STATUS_RUNNING = "running"
ANALYSIS_STATUS_COMPLETED = "completed"
ANALYSIS_STATUS_FAILED = "failed"
ANALYSIS_STATUS_CANCELLED = "cancelled"
ANALYSIS_STATUSES = (
    ANALYSIS_STATUS_RUNNING,
    ANALYSIS_STATUS_COMPLETED,
    ANALYSIS_STATUS_FAILED,
    ANALYSIS_STATUS_CANCELLED,
)

STRUCTURAL_ANALYSIS_SCHEMA_VERSION = 1
STRUCTURAL_LIVENESS_POLICY_VERSION = 1

ACTIVITY_KIND_USER_TEXT = "user_text"
ACTIVITY_KIND_ASSISTANT_TEXT = "assistant_text"
ACTIVITY_KIND_ASSISTANT_THINKING = "assistant_thinking"
ACTIVITY_KIND_TOOL_PAIR = "tool_pair"
ACTIVITY_KIND_PENDING_TOOL_CALL = "pending_tool_call"
ACTIVITY_KIND_ORPHAN_TOOL_RESULT = "orphan_tool_result"
ACTIVITY_KIND_COMPACTION = "compaction"
ACTIVITY_KIND_SESSION_EVENT = "session_event"
ACTIVITY_KIND_CUSTOM_EVENT = "custom_event"
ACTIVITY_KINDS = (
    ACTIVITY_KIND_USER_TEXT,
    ACTIVITY_KIND_ASSISTANT_TEXT,
    ACTIVITY_KIND_ASSISTANT_THINKING,
    ACTIVITY_KIND_TOOL_PAIR,
    ACTIVITY_KIND_PENDING_TOOL_CALL,
    ACTIVITY_KIND_ORPHAN_TOOL_RESULT,
    ACTIVITY_KIND_COMPACTION,
    ACTIVITY_KIND_SESSION_EVENT,
    ACTIVITY_KIND_CUSTOM_EVENT,
)

ACTIVITY_TEXT_KIND_DETERMINISTIC = "deterministic"
ACTIVITY_TEXT_KIND_TOOL_SUMMARY = "tool_summary"
ACTIVITY_TEXT_KIND_UNAVAILABLE = "unavailable"
ACTIVITY_TEXT_KINDS = (
    ACTIVITY_TEXT_KIND_DETERMINISTIC,
    ACTIVITY_TEXT_KIND_TOOL_SUMMARY,
    ACTIVITY_TEXT_KIND_UNAVAILABLE,
)

ACTIVITY_TEXT_STATUS_PENDING = "pending"
ACTIVITY_TEXT_STATUS_COMPLETED = "completed"
ACTIVITY_TEXT_STATUS_SKIPPED = "skipped"
ACTIVITY_TEXT_STATUS_FAILED = "failed"
ACTIVITY_TEXT_STATUSES = (
    ACTIVITY_TEXT_STATUS_PENDING,
    ACTIVITY_TEXT_STATUS_COMPLETED,
    ACTIVITY_TEXT_STATUS_SKIPPED,
    ACTIVITY_TEXT_STATUS_FAILED,
)

EPISODE_STATUS_OPEN = "open"
EPISODE_STATUS_CLOSED = "closed"
EPISODE_STATUSES = (EPISODE_STATUS_OPEN, EPISODE_STATUS_CLOSED)

EPISODE_CLOSE_REASON_COMPACTION = "compaction"
EPISODE_CLOSE_REASON_TIME_GAP = "time_gap"
EPISODE_CLOSE_REASON_TRANSCRIPT_END = "transcript_end"
EPISODE_CLOSE_REASON_CURRENT_CURSOR = "current_cursor"
EPISODE_CLOSE_REASONS = (
    EPISODE_CLOSE_REASON_COMPACTION,
    EPISODE_CLOSE_REASON_TIME_GAP,
    EPISODE_CLOSE_REASON_TRANSCRIPT_END,
    EPISODE_CLOSE_REASON_CURRENT_CURSOR,
)

SESSION_SNAPSHOT_STATUS_READY_FOR_INTERPRETATION = "ready_for_interpretation"
SESSION_SNAPSHOT_STATUSES = (SESSION_SNAPSHOT_STATUS_READY_FOR_INTERPRETATION,)

SESSION_INTERPRETATION_STATUS_COMPLETED = "completed"
SESSION_INTERPRETATION_STATUS_BLOCKED = "blocked"
SESSION_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES = "skipped_no_claim_sources"
SESSION_INTERPRETATION_STATUSES = (
    SESSION_INTERPRETATION_STATUS_COMPLETED,
    SESSION_INTERPRETATION_STATUS_BLOCKED,
    SESSION_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES,
)

EPISODE_INTERPRETATION_STATUS_COMPLETED = "completed"
EPISODE_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES = "skipped_no_claim_sources"
EPISODE_INTERPRETATION_STATUS_FAILED = "failed"
EPISODE_INTERPRETATION_STATUSES = (
    EPISODE_INTERPRETATION_STATUS_COMPLETED,
    EPISODE_INTERPRETATION_STATUS_SKIPPED_NO_CLAIM_SOURCES,
    EPISODE_INTERPRETATION_STATUS_FAILED,
)

SESSION_INTERPRETATION_BLOCKED_REASON_PHASE_5A_NOT_READY = "phase_5a_not_ready"
SESSION_INTERPRETATION_BLOCKED_REASON_PARENT_TRANSCRIPT_NOT_INGESTED = "parent_transcript_not_ingested"
SESSION_INTERPRETATION_BLOCKED_REASON_SOURCE_ORIGIN_INCOMPLETE = "source_origin_incomplete"
SESSION_INTERPRETATION_BLOCKED_REASONS = (
    SESSION_INTERPRETATION_BLOCKED_REASON_PHASE_5A_NOT_READY,
    SESSION_INTERPRETATION_BLOCKED_REASON_PARENT_TRANSCRIPT_NOT_INGESTED,
    SESSION_INTERPRETATION_BLOCKED_REASON_SOURCE_ORIGIN_INCOMPLETE,
)

SESSION_INTERPRETATION_QUALITY_STATUS_HEALTHY = "healthy"
SESSION_INTERPRETATION_QUALITY_STATUS_DEGRADED = "degraded"
SESSION_INTERPRETATION_QUALITY_STATUS_FAILED = "failed"
SESSION_INTERPRETATION_QUALITY_STATUS_NOT_ASSESSED = "not_assessed"
SESSION_INTERPRETATION_QUALITY_STATUS_ASSESSMENT_FAILED = "assessment_failed"
SESSION_INTERPRETATION_QUALITY_STATUSES = (
    SESSION_INTERPRETATION_QUALITY_STATUS_HEALTHY,
    SESSION_INTERPRETATION_QUALITY_STATUS_DEGRADED,
    SESSION_INTERPRETATION_QUALITY_STATUS_FAILED,
    SESSION_INTERPRETATION_QUALITY_STATUS_NOT_ASSESSED,
    SESSION_INTERPRETATION_QUALITY_STATUS_ASSESSMENT_FAILED,
)

SESSION_INTERPRETATION_QUALITY_REASON_BLOCKED_INTERPRETATION = "blocked_interpretation"
SESSION_INTERPRETATION_QUALITY_REASON_SKIPPED_NO_CLAIM_SOURCES = "skipped_no_claim_sources"
SESSION_INTERPRETATION_QUALITY_REASON_OUTDATED_DERIVATION = "outdated_derivation"
SESSION_INTERPRETATION_QUALITY_REASON_SUPERSEDED_SNAPSHOT = "superseded_snapshot"
SESSION_INTERPRETATION_QUALITY_REASON_DETERMINISTIC_INTEGRITY_FAILED = "deterministic_integrity_failed"
SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_DEGRADED = "semantic_degraded"
SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_FAILED = "semantic_failed"
SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_PENDING = "semantic_assessment_pending"
SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_FAILED = "semantic_assessment_failed"
SESSION_INTERPRETATION_QUALITY_REASONS = (
    SESSION_INTERPRETATION_QUALITY_REASON_BLOCKED_INTERPRETATION,
    SESSION_INTERPRETATION_QUALITY_REASON_SKIPPED_NO_CLAIM_SOURCES,
    SESSION_INTERPRETATION_QUALITY_REASON_OUTDATED_DERIVATION,
    SESSION_INTERPRETATION_QUALITY_REASON_SUPERSEDED_SNAPSHOT,
    SESSION_INTERPRETATION_QUALITY_REASON_DETERMINISTIC_INTEGRITY_FAILED,
    SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_DEGRADED,
    SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_FAILED,
    SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_PENDING,
    SESSION_INTERPRETATION_QUALITY_REASON_SEMANTIC_ASSESSMENT_FAILED,
)

SESSION_INTERPRETATION_DERIVATION_STATUS_CURRENT = "current"
SESSION_INTERPRETATION_DERIVATION_STATUS_OUTDATED = "outdated"
SESSION_INTERPRETATION_DERIVATION_STATUS_SUPERSEDED = "superseded"
SESSION_INTERPRETATION_DERIVATION_STATUSES = (
    SESSION_INTERPRETATION_DERIVATION_STATUS_CURRENT,
    SESSION_INTERPRETATION_DERIVATION_STATUS_OUTDATED,
    SESSION_INTERPRETATION_DERIVATION_STATUS_SUPERSEDED,
)

SESSION_INTERPRETATION_DETERMINISTIC_STATUS_PASSED = "passed"
SESSION_INTERPRETATION_DETERMINISTIC_STATUS_FAILED = "failed"
SESSION_INTERPRETATION_DETERMINISTIC_STATUS_NOT_APPLICABLE = "not_applicable"
SESSION_INTERPRETATION_DETERMINISTIC_STATUSES = (
    SESSION_INTERPRETATION_DETERMINISTIC_STATUS_PASSED,
    SESSION_INTERPRETATION_DETERMINISTIC_STATUS_FAILED,
    SESSION_INTERPRETATION_DETERMINISTIC_STATUS_NOT_APPLICABLE,
)

SESSION_INTERPRETATION_SEMANTIC_STATUS_PASSED = "passed"
SESSION_INTERPRETATION_SEMANTIC_STATUS_DEGRADED = "degraded"
SESSION_INTERPRETATION_SEMANTIC_STATUS_FAILED = "failed"
SESSION_INTERPRETATION_SEMANTIC_STATUS_NOT_ASSESSED = "not_assessed"
SESSION_INTERPRETATION_SEMANTIC_STATUS_ASSESSMENT_FAILED = "assessment_failed"
SESSION_INTERPRETATION_SEMANTIC_STATUSES = (
    SESSION_INTERPRETATION_SEMANTIC_STATUS_PASSED,
    SESSION_INTERPRETATION_SEMANTIC_STATUS_DEGRADED,
    SESSION_INTERPRETATION_SEMANTIC_STATUS_FAILED,
    SESSION_INTERPRETATION_SEMANTIC_STATUS_NOT_ASSESSED,
    SESSION_INTERPRETATION_SEMANTIC_STATUS_ASSESSMENT_FAILED,
)

SOURCE_ORIGIN_LOCAL = "local"
SOURCE_ORIGIN_INHERITED = "inherited"
SOURCE_ORIGIN_MIXED = "mixed"
SOURCE_ORIGIN_UNKNOWN = "unknown"
SOURCE_ORIGINS = (
    SOURCE_ORIGIN_LOCAL,
    SOURCE_ORIGIN_INHERITED,
    SOURCE_ORIGIN_MIXED,
    SOURCE_ORIGIN_UNKNOWN,
)

DURABLE_MEMORY_STATUS_CANDIDATE = "candidate"
DURABLE_MEMORY_STATUS_PROMOTED = "promoted"
DURABLE_MEMORY_STATUS_QUARANTINED = "quarantined"
DURABLE_MEMORY_STATUS_REJECTED = "rejected"
DURABLE_MEMORY_STATUS_ARCHIVED = "archived"
DURABLE_MEMORY_STATUSES = (
    DURABLE_MEMORY_STATUS_CANDIDATE,
    DURABLE_MEMORY_STATUS_PROMOTED,
    DURABLE_MEMORY_STATUS_QUARANTINED,
    DURABLE_MEMORY_STATUS_REJECTED,
    DURABLE_MEMORY_STATUS_ARCHIVED,
)

DURABLE_MEMORY_ARCHIVED_REASON_SUPERSEDED = "superseded"
DURABLE_MEMORY_ARCHIVED_REASON_STALE = "stale"
DURABLE_MEMORY_ARCHIVED_REASON_MANUALLY_RETIRED = "manually_retired"
DURABLE_MEMORY_ARCHIVED_REASON_SOURCE_INVALIDATED = "source_invalidated"
DURABLE_MEMORY_ARCHIVED_REASONS = (
    DURABLE_MEMORY_ARCHIVED_REASON_SUPERSEDED,
    DURABLE_MEMORY_ARCHIVED_REASON_STALE,
    DURABLE_MEMORY_ARCHIVED_REASON_MANUALLY_RETIRED,
    DURABLE_MEMORY_ARCHIVED_REASON_SOURCE_INVALIDATED,
)

DURABLE_MEMORY_RELATION_TYPE_NOVEL = "novel"
DURABLE_MEMORY_RELATION_TYPE_DUPLICATE = "duplicate"
DURABLE_MEMORY_RELATION_TYPE_REINFORCES = "reinforces"
DURABLE_MEMORY_RELATION_TYPE_REFINES = "refines"
DURABLE_MEMORY_RELATION_TYPE_CONFLICTS = "conflicts"
DURABLE_MEMORY_RELATION_TYPE_SUPERSEDES = "supersedes"
DURABLE_MEMORY_RELATION_TYPE_STALE_SIGNAL = "stale_signal"
DURABLE_MEMORY_RELATION_TYPES = (
    DURABLE_MEMORY_RELATION_TYPE_NOVEL,
    DURABLE_MEMORY_RELATION_TYPE_DUPLICATE,
    DURABLE_MEMORY_RELATION_TYPE_REINFORCES,
    DURABLE_MEMORY_RELATION_TYPE_REFINES,
    DURABLE_MEMORY_RELATION_TYPE_CONFLICTS,
    DURABLE_MEMORY_RELATION_TYPE_SUPERSEDES,
    DURABLE_MEMORY_RELATION_TYPE_STALE_SIGNAL,
)

DURABLE_MEMORY_SOURCE_KIND_CLAIM = "claim"
DURABLE_MEMORY_SOURCE_KIND_SUPPORTING_CONTEXT = "supporting_context"
DURABLE_MEMORY_SOURCE_KINDS = (
    DURABLE_MEMORY_SOURCE_KIND_CLAIM,
    DURABLE_MEMORY_SOURCE_KIND_SUPPORTING_CONTEXT,
)

MEMORY_PROJECTION_COLLECTION_NAME = "pi_memory_records"
MEMORY_PROJECTION_RECORD_TYPE_SESSION_CLAIM = "session_claim"
MEMORY_PROJECTION_RECORD_TYPE_DURABLE_MEMORY = "durable_memory"
MEMORY_PROJECTION_RECORD_TYPES = (
    MEMORY_PROJECTION_RECORD_TYPE_SESSION_CLAIM,
    MEMORY_PROJECTION_RECORD_TYPE_DURABLE_MEMORY,
)

MEMORY_LAYER_SHORT_TERM = "short_term"
MEMORY_LAYER_LONG_TERM = "long_term"
MEMORY_LAYERS = (MEMORY_LAYER_SHORT_TERM, MEMORY_LAYER_LONG_TERM)

MEMORY_PROJECTION_STATUS_PENDING = "pending"
MEMORY_PROJECTION_STATUS_INDEXED = "indexed"
MEMORY_PROJECTION_STATUS_STALE = "stale"
MEMORY_PROJECTION_STATUS_FAILED = "failed"
MEMORY_PROJECTION_STATUS_DELETED = "deleted"
MEMORY_PROJECTION_STATUSES = (
    MEMORY_PROJECTION_STATUS_PENDING,
    MEMORY_PROJECTION_STATUS_INDEXED,
    MEMORY_PROJECTION_STATUS_STALE,
    MEMORY_PROJECTION_STATUS_FAILED,
    MEMORY_PROJECTION_STATUS_DELETED,
)
