export {
	attachWorktreeDir,
	branchName,
	ensureWorktreeLabel,
	findWorktreeRecord,
	getOrCreateWorktree,
	gitWorktreeRecords,
	labelFromWorktreePath,
	listWorktrees,
	parseWorktreeList,
	validateProtectedCheckout,
	validateWorktreePath,
	type WorktreeResult,
	type WorktreeSummary,
} from "../../../workspace/src/worktree.ts";
